### ISSUE TITLE
License

### ISSUE THREAD

**Issue by eljost** [sanha0213/ValleyRidge#1]
Hi,
thanks for your work. Is it possible to put the code under an open source so people can modify/use it? Right now the missing license is kind of a bummer ([choosealicense.com/no-permission](https://choosealicense.com/no-permission/)).

Best regards,
Johannes

**Comment by Jonathan-Goodman** [comment]
Thank you for this. We have now added the MIT license information to the repository. I hope this makes it more useful for you.
